sonar.projectKey=vinjatovix_agro-back
sonar.organization=vinjatovix
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/tests/**/*, **/node_modules/**/*, **/routes/**/*, **/cucumber.mjs, **/jest.config.ts, **/docker/mongo/mongo-init.js, **/logger.plugin.ts, setupTests.ts
