export const MONGO_ERROR_CODES = {
  BAD_VALUE: 2,
  WRONG_TYPE: 5,
  NAMESPACE_EXISTS: 48,
  DUPLICATE_INDEX: 65,
  IMMUTABLE_FIELD: 66,
  CANNOT_CREATE_INDEX: 67,
  INDEX_ALREADY_EXISTS: 68,
  INDEX_OPTIONS_CONFLICT: 85,
  INDEX_KEY_SPECS_CONFLICT: 86,
  VALIDATION_ERROR: 121,
  BSON_OBJECT_TOO_LARGE: 10334,
  DUPLICATE_KEY: 11000,
  PATH_COLLISION: 31249
} as const;
